# dataset
dataset_name: "EICU"
data_root: "/home/yxchen/Projects/machine_unlearning_v2/data"
extra_eval_datasets: null
protected_attr: "ethnicity"
task_type: "shock" # "mortality", "shock"

# model
model_name: "transformer"
device: "cuda"

transformer:
  depth: 2            
  heads: 8            
  dim_head: 64        
  ff_dim: 256         
  mlp_head_hidden_dim: null  
  use_class_token: true
  pool: "cls"        
  dropout: 0.0
  mlp_head_dropout: 0.0
  pe_method: null    
  pe_max_len: 5000
  activation: "gelu"
  sigmoid: true     

# training for the original model
seed: 512
lr: 0.0001
epochs: 10
batch_size: 1024
early_stop_patience: 10

# unlearning method
unlearning_method: "FU"

# FU hyperparams
unlearning_lr: 0.0005
unlearning_iterations: 2
weight_cls: 0.1
weight_fair: 0.3
weight_remain: 0.4

# unlearning
exp_root: ""
num_runs: 1
target_step: -1  # -1 means run all steps
sample_method: "random"
remove_ratio: 0.1
step_ratio: 0.01
target_protected_values: null

# evaluation
eval_fairness: 1
eval_mia: 1
eval_model_inversion: 1

# mia hyperparameters
mia_kwargs:
    sample_test_size: 500

# model inversion hyperparameters
model_inversion_kwargs:
    iters: 100
    noise_std_range: [0.01, 0.05]
    l1_reg: 1e-3
    k: 10
    multi_restart: 1
    inv_per_class: 256
